version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: poc-postgres
    environment:
      POSTGRES_DB: campaignApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: beko1
    ports:
      - "5432:5432"

  app:
    build: .
    image: poc-app
    container_name: poc-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://poc-postgres:5432/campaignApi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=beko1
